sudo: false

language: python

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35

env:
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=flake8
  - TOXENV=coverage

before_install:
      - pip install codecov
after_success:
      - codecov

install: pip install -U tox

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kragniz
  password:
    secure: 3CodiqpXEYgC+tcYwTnDLMMdGYUQ5w474aCzacRo6J7ZJgBGeIImF/AGij65DXa+nw8IFWrFXgJhd6ViZvjcuhMWrLctUNIBETklYbMBt127L+wzMuhQ32BZxJeoXo9jf5+7Bayw3FuiH0BYqA6qkt6iMmDaQFhKp4mDGU8WmuAXGxr2mGP+ELTx+QqdnQwMdnJJERqXGUvz0DlhX+JoQRRfUCMJ0XjfyUXl1LxUTItFtt7ciJrTaBFkdq426YXHdbyYj3ocERu+PSs7EWjBFR3XhL/mZGVxVDJZhO7dCMjfQvLHQiGGivIu8+4Hm98EhZ1bFgYD48jnYaFWVV7eNoj8dm/CinVMtEEI77levj1HXl7nXQn78tEL7AKpKyTR9Rx/e+PXn6aVgRVhpkWgQAL/vDcWYVp86e+Vl4xLhKXQtK2ZppFDQ9gWbmo2yBQVbzMMJ3ygb1qen8xYnxyPVK96az46nDvgoUZO8tRikF88RZBwV7aK3P9eQhA/QdVIlgQUI68ZbK6UxSpC32UvWrIqBIfrb8r+5qOJVuPvSlxDaHnk41E91kBsydCyxR62HDgahs1tPOWV4n8Hb8U8Yb6o+mczao7k77rvxFv6kQiE/8uihirGFP/3jbd/asQlRO58GNF48nJDhLo8uqvfiZg48IDweA4RGiXVNLQKvYM=
  on:
    tags: true
    repo: kragniz/python-pixiv
    condition: $TOXENV == py27
